[book]
authors = ["Unbreathable"]
language = "en"
multilingual = false
src = "src"
title = "Liphium Town Documentation"

[preprocessor.tabs]

[output.html]
additional-css = ["theme/tabs.css"]
additional-js = ["theme/tabs.js"]
